paths:
  home: "/path/to/your/crispr-vus"
  pathdata: "data"
  resultPath: "results_1tissue"
  raw_dir: "raw"
  robj_dir: "Robj"
  CRISPRplots_dir: "_CRISPR_plots"
  figuresPath: "_figures_source"
  DRplots_dir: "_DR_plots"
  tablesPath: "_tables_source"

files:
  gene_annot_file: "gene_identifiers_20241212.csv"
  CMP_annot_file: "model_list_20241120.csv"
  crispr_file: "CRISPRGeneEffect.csv"
  cl_variants_file: "mutations_all_20241212.csv"
  gdsc1_file: "GDSC1_fitted_dose_response_27Oct23.csv"
  gdsc2_file: "GDSC2_fitted_dose_response_27Oct23.csv"
  intogen_file: "2024-06-18_IntOGen-Drivers/Compendium_Cancer_Genes.tsv"
  drug_target_info_file: "drug-target_data_hgvs_clean_Goncalves_et_all.txt"
  cl_tissue_colors_file: "CL_tissue_ctype_colors.xlsx"
  cancer_match_file_v3: "intOGen ctype mapping_AS_v3.csv"
  cancer_match_file_v2: "intOGen ctype mapping_AS_v2.csv"
  benchmark_file: "benchmark-datasets.xlsx"
  tractability_file: "Tractability_pacini_et_al_2024.txt"
  loc_file: "only_included_VUS_location_GRCh38_ctype_updated.csv"
  cosmic_mutant_file: "Cosmic_GenomeScreensMutant_Tsv_v101_GRCh38/Cosmic_GenomeScreensMutant_v101_GRCh38.tsv.gz"
  cosmic_sample_file: "Cosmic_Sample_Tsv_v101_GRCh38/Cosmic_Sample_v101_GRCh38.tsv.gz"
  cosmic_classification_file: "Cosmic_Classification_Tsv_v101_GRCh38/Cosmic_Classification_v101_GRCh38.tsv.gz"
  cosmic_mutant_file_new: "Cosmic_GenomeScreensMutant_Tsv_v104_GRCh38/Cosmic_GenomeScreensMutant_v104_GRCh38.tsv.gz"
  cosmic_sample_file_new: "Cosmic_Sample_Tsv_v104_GRCh38/Cosmic_Sample_v104_GRCh38.tsv.gz"
  cosmic_classification_file_new: "Cosmic_Classification_Tsv_v104_GRCh38/Cosmic_Classification_v104_GRCh38.tsv.gz"
  civic_file: "01-May-2025-ClinicalEvidenceSummaries.tsv"
  civic_mapping_file: "CivicDB_mapping.csv"
  open_tract_file: "OpenTargets_tractability_20250829.tsv"

robj_files:
  ADaM: "ADaM.RData"
  FiPer_outputs: "FiPer_outputs.RData"
  basal_exp: "basal_exp.RData"
  ensembl: "ensembe.RData"